# Generated by Django 5.2.6 on 2025-11-17 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "genres",
                    models.CharField(help_text="쉼표로 구분된 장르", max_length=255),
                ),
                ("equipments", models.TextField()),
                ("portfolio_url", models.URLField(blank=True)),
                ("image_url", models.URLField()),
                ("history", models.TextField()),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artist_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Jazz", "Jazz"),
                            ("Rock", "Rock"),
                            ("Electronic", "Electronic"),
                            ("Hip-Hop", "Hip-Hop"),
                            ("Indie", "Indie"),
                            ("디제잉", "디제잉"),
                            ("북토크", "북토크"),
                            ("스탠드업 코미디", "스탠드업 코미디"),
                            ("클래식", "클래식"),
                            ("R&B", "R&B"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("서울", "서울"),
                            ("경기", "경기"),
                            ("인천", "인천"),
                            ("강원", "강원"),
                            ("충청", "충청"),
                            ("전라", "전라"),
                            ("경상", "경상"),
                            ("제주", "제주"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("venue_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("price", models.PositiveIntegerField()),
                ("is_free", models.BooleanField(default=False)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("standing", "Standing"),
                            ("seat", "Seat"),
                            ("free", "Free"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image_url", models.URLField()),
                ("allow_dyve_reservation", models.BooleanField(default=True)),
                ("advertise", models.BooleanField(default=False)),
                (
                    "artists",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="core.artist"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("performance_update", models.BooleanField(default=True)),
                ("proposal", models.BooleanField(default=True)),
                ("reservation", models.BooleanField(default=True)),
                ("marketing", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_setting",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("seat", models.CharField(blank=True, max_length=255)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("standing", "Standing"),
                            ("seat", "Seat"),
                            ("free", "Free"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                ("qr_code", models.CharField(max_length=255)),
                ("reservation_code", models.CharField(max_length=50, unique=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="core.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("라이브클럽", "라이브클럽"),
                            ("공연장", "공연장"),
                            ("갤러리", "갤러리"),
                            ("카페", "카페"),
                            ("루프탑", "루프탑"),
                            ("바/펍", "바/펍"),
                            ("소극장", "소극장"),
                            ("멀티홀", "멀티홀"),
                            ("연습실", "연습실"),
                            ("기타", "기타"),
                        ],
                        max_length=50,
                    ),
                ),
                ("genres", models.TextField()),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("서울", "서울"),
                            ("경기", "경기"),
                            ("인천", "인천"),
                            ("강원", "강원"),
                            ("충청", "충청"),
                            ("전라", "전라"),
                            ("경상", "경상"),
                            ("제주", "제주"),
                        ],
                        max_length=50,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("capacity", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("equipments", models.TextField()),
                ("image_url", models.URLField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_tickets", models.PositiveIntegerField()),
                ("settled_amount", models.PositiveIntegerField()),
                ("settled_at", models.DateTimeField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="core.event",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="core.space",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver_artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_proposals",
                        to="core.artist",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receiver_space",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_proposals",
                        to="core.space",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="event",
            name="space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="core.space",
            ),
        ),
    ]
