# Generated by Django 5.2.6 on 2025-11-19 08:07

from django.db import migrations, models


def convert_entry_types(apps, schema_editor):
    Event = apps.get_model("core", "Event")
    Reservation = apps.get_model("core", "Reservation")
    Event.objects.filter(entry_type="free").update(entry_type="general")
    Reservation.objects.filter(entry_type="free").update(entry_type="general")


def revert_entry_types(apps, schema_editor):
    Event = apps.get_model("core", "Event")
    Reservation = apps.get_model("core", "Reservation")
    Event.objects.filter(entry_type="general").update(entry_type="free")
    Reservation.objects.filter(entry_type="general").update(entry_type="free")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_venue"),
    ]

    operations = [
        migrations.RunPython(convert_entry_types, revert_entry_types),
        migrations.AlterField(
            model_name="event",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("general", "General Admission"),
                    ("seat", "Seat"),
                    ("standing", "Standing"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("general", "General Admission"),
                    ("seat", "Seat"),
                    ("standing", "Standing"),
                ],
                max_length=20,
            ),
        ),
    ]
