# Generated by Django 5.2.6 on 2025-11-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_event_entry_type_alter_reservation_entry_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("밴드", "밴드"),
                    ("싱어송라이터", "싱어송라이터"),
                    ("DJ", "DJ"),
                    ("힙합 크루", "힙합 크루"),
                    ("재즈 앙상블", "재즈 앙상블"),
                    ("클래식 앙상블", "클래식 앙상블"),
                    ("국악 프로젝트", "국악 프로젝트"),
                    ("퍼포먼스 아티스트", "퍼포먼스 아티스트"),
                    ("보컬 그룹", "보컬 그룹"),
                    ("프로듀서 팀", "프로듀서 팀"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="space",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="event",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("입장확인", "입장확인"),
                    ("좌석", "좌석"),
                    ("스탠딩", "스탠딩"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("입장확인", "입장확인"),
                    ("좌석", "좌석"),
                    ("스탠딩", "스탠딩"),
                ],
                max_length=20,
            ),
        ),
    ]
